### ISSUE TITLE
Being able to compare DCE compatibility with a program.

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#1]
I would like to write a script that computes a compatibility *ratio* of a software with DCE, ie, to count the number of unavailable syscalls in DCE to make the program work (I have the choice to use between 2 programs on DCE and I am looking at a way to find the easier one to make work).

My idea so far is to run "nm" on the program binary (with symbols), intersect the list with libc prototypes and then intersect the result on DCE syscalls. But I don't know the best way to retrieve sys functions. Any hint ?

**Comment by thehajime** [comment]
you may try and twaek the utils/elfread script, which counts the number of unimplemented functions, I guess.

https://github.com/direct-code-execution/ns-3-dce/blob/master/utils/elfread

I don't quite remember because it's written by Frederic Furbani, ex-developer of dce.

**Comment by teto** [comment]
Thanks but I will not have the time to do it I think. I close it maybe it can be reopened later

**Comment by thehajime** [comment]
I tried elfread script and seems to be working in my environment (FC21 64bits, readelf version 2.24). you might just try it by ./utils/elfread (your binary).
