### ISSUE TITLE
How to handle compiler warning " function is dangerous and should not be used."

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#17]
Hi,

I've recently upgraded gcc/clang and it generates a lot more (valid) errors/warnings than before. I am preparing a patch to fix those but there is one case I don't know how to handle:
```
char tmp[PATH_MAX + 1];
cwd = getwd (tmp, sizeof(tmp));
TEST_ASSERT_UNEQUAL (cwd, 0);
```
gcc generates:
dce/build/../test/test-fd-simple.cc:320: AVERTISSEMENT: the `getwd' function is dangerous and should not be used.
It is advised to use getcwd instead. I wonder if it would be wise to assert when "dce_getwd" is in use and recommand people to modify their programs to use getcwd instead, thus we could remove "getwd" from the test. Do you know any program using getwd it could be a problem with ?

**Comment by thehajime** [comment]
I wasn't so careful to clang so far. if we can replace/hide getwd() by getcwd() etc, that would be okay for the upstream.

I'm not aware of which applications use getwd() but don't want to bring degradations with any future fixes.

**Comment by teto** [comment]
Fix in https://github.com/direct-code-execution/ns-3-dce/pull/33

**Comment by tomhenderson** [comment]
I noticed that the patch was reverted after this issue was closed; I am seeing this warning again:

test-fd-simple.cc:320: warning: the `getwd' function is dangerous and should not be used.
