### ISSUE TITLE
Problem with running scripts under "myscripts"

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#3]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
`̀``

Result of ./waf configure
```
 INSERT  ./waf configure --with-ns3=$HOME/ns3off/install                                            1  16:55:19   clock_support 
Setting top to                           : /home/teto/dce 
Setting out to                           : /home/teto/dce/build 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for pkg-config version >= '0.0.0' : yes 
Checking for -Wl,--soname=foo              : yes 
Checking for ns3-core (ns3-dev)            : yes 
Checking for ns3-network (ns3-dev)         : yes 
Checking for ns3-internet (ns3-dev)        : yes 
Checking for ns3-point-to-point (ns3-dev)  : yes 
Checking for ns3-tap-bridge (ns3-dev)      : yes 
Checking for ns3-netanim (ns3-dev)         : yes 
Checking for ns3-wifi (ns3-dev)            : yes 
Checking for ns3-csma (ns3-dev)            : yes 
Checking for ns3-mobility (ns3-dev)        : yes 
Checking for ns3-point-to-point-layout (ns3-dev) : yes 
Checking for ns3-mpi (ns3-dev)                   : yes 
Checking for ns3-lte (ns3-dev)                   : yes 
Checking for ns3-visualizer (None)               : not found 
Checking for ns3-applications (ns3-dev)          : yes 
Checking for ns3-fd-net-device (ns3-dev)         : yes 
Checking for header stdint.h                     : yes 
Checking for header inttypes.h                   : yes 
Checking for header sys/inttypes.h               : not found 
Checking for header sys/types.h                  : yes 
Checking for header sys/stat.h                   : yes 
Checking for header dirent.h                     : yes 
Checking for library dl                          : yes 
Checking for glibc get_cpu_features              : yes 
Checking for glibc __secure_getenv               : no 
Checking for header valgrind/valgrind.h          : yes 
Checking for header valgrind/memcheck.h          : yes 
Checking for ns3-flow-monitor (ns3-dev)          : yes 
Checking for 'gcc' (c compiler)                  : /usr/bin/gcc 
Checking for header hook-manager.h               : not found 
Checking for program valgrind                    : /usr/bin/valgrind 
Checking for program doxygen                     : /usr/bin/doxygen 
Checking for header netinet/sctp.h               : not found 
Checking for program python                      : /usr/bin/python 
Checking for python version                      : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR         : yes 
Checking for program python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python2.7-config 
Checking for header Python.h                                              : yes 
Checking for pybindgen location                                           : not found 
Python module pybindgen                                                   : not found 
pybindgen missing => no python bindings
---- Summary of optional NS-3 features:
Static build                  : not enabled (option --enable-static not selected)
Logging                       : enabled
Assert checks                 : enabled
Code coverage                 : not enabled (option --enable-gcov not selected)
Example programs              : enabled
Test programs                 : enabled
Debug Symbols                 : enabled
ELF magic loader              : not enabled (elf-loader not found)
Aspect-based tracing          : not enabled (libaspect not found)
sctp-tools-dev                : not enabled (sctp-tools (netinet/sctp.h) not found)
'configure' finished successfully (0.732s)
```
Then I ran 2 builds (everytime I did a ./waf clean beforehand)
https://transfer.sh/Un8w4/out-simple.txt
https://transfer.sh/aMk0n/out-verbose.txt

build/build_status.py
```
#! /usr/bin/env python                                                                                                              

# Programs that are runnable.
ns3_runnable_programs = ['dce-test', 'test', 'dce-tcp-simple', 'dce-udp-simple', 'dce-ccnd-simple', 'dce-ccnd-short-stuff', 'dce-tap-udp-echo', 'dce-tap-ccnd', 'dce-tap-vlc', 'dce-bash-simple', 'dce-ccn-cache', 'dce-iperf', 'dce-iperf-emulation', 'linear-udp-perf', 'dce-test-netlink', 'test-runner', 'bin/test-runner']

# Scripts that are runnable.
ns3_runnable_scripts = []
 ```
and build/config.log
https://transfer.sh/1h5oqV/config.log

Tell me if you need any other log or if I should try sthg else

**Comment by thehajime** [comment]
are you using the latest ns-3-dce ?

I guess 12e77466c8891609c5a496de466f2ea38895f49e should fix this issue.

**Comment by teto** [comment]
I've started debugging with printf waf and found the problem fixed by your patch :s rebased on the latest ns3 and it fixes it.
