### ISSUE TITLE
Documentation: replace net-next-sim with libos

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#30]
Shouldn't we replace links to net-next-sim with libos in doc: 
https://www.nsnam.org/docs/dce/manual/html/dce-user-kernel.html
?

I have not tried it yet, does libos work with mptcp ? ie. can both trees be easily merged ?

**Comment by thehajime** [comment]
> Shouldn't we replace links to net-next-sim with libos in doc: 
> https://www.nsnam.org/docs/dce/manual/html/dce-user-kernel.html
> ?

in ns-3-dce document we still stick on 2.6.36 kernel of net-next-sim and the next-next-sim repo still uses old directly structure (i.e., arch/sim) so the manual still valid.

once we finished to clean up/update libos code or to make those old kernel unsupported with DCE, the manual can update as well.
(libos code is still not a stable one)

> I have not tried it yet, does libos work with mptcp ? ie. can both trees be easily merged ?

yes. though the following branch is a snapshot, it basically can be merged without much pain.

https://github.com/libos-nuse/net-next-nuse/tree/mptcp_trunk_libos

**Comment by teto** [comment]
Considering there is no clear advnatage of using libos for DCE over net-next-sim and that in the future it might even be lkl, I deem https://github.com/direct-code-execution/ns-3-dce/pull/35 enough as a documentation
