### ISSUE TITLE
get rid of "#ifdef KERNEL_STACK"

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#44]
I was thinking about packaging DCE (for debian for instance) and having to recompile DCE to enable this feature is not doable.
The --enable-kernel-stack could be removed and DCE could embed a copy of "include/sim-init.h" in DCE instead.

**Comment by thehajime** [comment]
I think we have different versions of sim-init.h so, removing `--enable-kernel-stack` is not useful in some case.
