### ISSUE TITLE
Allow to override values returned by DceNodeContext::UName

### ISSUE THREAD

**Issue by teto** [direct-code-execution/ns-3-dce#5]
Some programs parse the values returned by uname and exit if they are not pleased with the value.
It should be possible to override them.

**Comment by thehajime** [comment]
make sense.
maybe adding an attribute to ns3::DceManager() and access by DceManagerHelper::SetAttribute() would be the way.

**Comment by thehajime** [comment]
@teto I've started to implement this.

which member of struct utsname do you want to override or everything ?

```
struct utsname {
    char sysname[];    /* Operating system name (e.g., "Linux") */
    char nodename[];   /* Name within "some implementation-defined
                                     network" */
    char release[];    /* Operating system release (e.g., "2.6.28") */
    char version[];    /* Operating system version */
    char machine[];    /* Hardware identifier */
 #ifdef _GNU_SOURCE
    char domainname[]; /* NIS or YP domain name */
#endif
};
```

**Comment by teto** [comment]
For instance I am working with a program that has this kind of calls:
```
  if (sscanf(uts.release, "%d.%d.%d", &major, &minor, &patch) < 2) {
    LOG_FATAL(LOGF_SysLinux, "Cannot read information from uname, sorry");
  }
```
So I owuld say "release".

2015-06-25 17:19 GMT+02:00 Hajime Tazaki <notifications@github.com>:

**Comment by teto** [comment]
Also I noticed:
  if (kernelvercmp(major, minor, patch, 2, 2, 0) < 0) {
    LOG_FATAL(LOGF_SysLinux, "Kernel version not supported, sorry.");
  }

2015-06-26 16:44 GMT+02:00 Matt <mattator@gmail.com>:

**Comment by thehajime** [comment]
@teto okay, I will prepare an update and let you know.

**Comment by teto** [comment]
It's nothing urgent, I've overriden the configuration locally. thanks for
addressing this though.

2015-06-26 16:57 GMT+02:00 Hajime Tazaki <notifications@github.com>:

**Comment by thehajime** [comment]
added this feature in the tree. I will close this issue once the test passed.

**Comment by teto** [comment]
I know you would have preferred the use of the ns Attribute system. I might add that later when I will test again the program I needed this feature for.
