### ISSUE TITLE
dce documentation missguide

### ISSUE THREAD

**Issue by mvkrdndm** [direct-code-execution/ns-3-dce#54]
hi ,here i encounter this problem ,in dce 1.9 documention; installation steps mentions quagga-1.7 when i followed the steps it makes extra ns-3 installation. here is the link  
https://groups.google.com/forum/#!topic/ns-3-users/d7ikJEaJQLg

**Comment by teto** [comment]
Thanks for telling us.
The error is in this file:
https://github.com/direct-code-execution/ns-3-dce-quagga/blob/master/doc/source/getting-started.rst
if you are familiar with github, you can send a pull request else you will have to wait for hajime to fix it, I don't use quagga.
