### ISSUE TITLE
Any way to find built DCE configuration

### ISSUE THREAD

**Issue by srathi1** [direct-code-execution/ns-3-dce#79]
Hi Folks ,

Is there any way to find configuration file or config options of built NS3-DCE. I have VM with dce installed into it  but i wanna do some changes into it so i am curious if i can find previous configuration and change according to me. 

Thanks

**Comment by teto** [comment]
in the build or .waf folder, waf generates a file `c4nfig.py` IIRC, you can find the config used there.

**Comment by srathi1** [comment]
Sorry I didn't find any file name "c4nfig.py". I searched in the whole repo which is having everything including build folder also.

**Comment by teto** [comment]
I just checked look into build/config.log and build/c4che/_cache.py
