### ISSUE TITLE
Assert Failed Error in DCE

### ISSUE THREAD

**Issue by srathi1** [direct-code-execution/ns-3-dce#81]
Hi folks,

I am trying to run models with dce , everything built successfully but when i am running simulation it ends with this error " **assert failed. cond="current ->process->pid == PthreadToPid (thread_handle)", file=../model/dce-pthread.cc, line=186**"

Even it was showing up with same kind of error in iperf example so i edit DCE_PATH and it works fine but not in case of my own models

I set the DCE_PATH and DCE_ROOT using the command "**./waf shell"**

Value of DCE_PATH is shown below after editing 

/home/testbed/Multispeak/dce/source/ns-3-dce/build/bin_dce:/home/testbed/FNCS-install/sbin:/home/testbed/FNCS-install/bin_dce:/usr/lib/gcc/x86_64-linux-gnu/5:/home/testbed/FNCS-install/lib:/home/testbed/Multispeak/dce/build/lib:/home/testbed/Multispeak/dce/source/ns-3-dce/build/lib:/home/testbed/Multispeak/dce/source/ns-3-dce/build/lib64:/home/testbed/Multispeak/dce/source/ns-3-dce/build/bin:/home/testbed/FNCS-install/lib:/home/testbed/FNCS-install/lib64:/home/testbed/FNCS-install/bin:/home/testbed/Multispeak/dce/build/bin

Value of DCE_ROOT

/home/testbed/Multispeak/dce/source/ns-3-dce/build:/usr/local

Can you please help me regarding this error. 

Thanks in advance

**Comment by teto** [comment]
How did you build DCE ? with bake or manually ? what version ? is this the DCE_PATH seen by DCE ? try to run it with NS_LOG=debug to get more details

**Comment by srathi1** [comment]
I build DCE with bake having personal configuration. After that i add models into DCE and build everything using waf. Models built and install perfectly but getting error while running them.

So i dig out into folder "file-0" and output of file "stderr" is shown below. Before you check with error let me tell you , i am using gsoap along with models. 

**Error 28 fault detected [no subcode]
"Protocol not available"
Detail: setsockopt TCP_NODELAY failed in soap_bind()**

**Comment by srathi1** [comment]
Hi , I tried to run my models with gdb and got the ouput shown below , do you have any idea what's wrong going on here 

Starting program: /home/testbed/Multispeak/dce/source/ns-3-dce/build/myscripts/multispeak/bin/RADICS_Exercise2_Utility1_AMI_1day 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed8f8700 (LWP 7917)]
[New Thread 0x7fffed0f7700 (LWP 7918)]
Use kernel: 0

Thread 1 "RADICS_Exercise" received signal SIGUSR1, User defined signal 1.
0x00007ffff3f9d269 in raise (sig=10) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
35	../sysdeps/unix/sysv/linux/pt-raise.c: No such file or directory.

Backtrace

#0  0x00007ffff3f9d269 in raise (sig=10) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
#1  0x00007ffff7ae52b3 in ns3::StackTrampoline::StackTrampoline (this=0x6d9410) at ../model/pthread-fiber-manager.cc:143
#2  0x00007ffff7ae2a41 in ns3::PthreadFiberManager::PthreadFiberManager (this=0x6d9020) at ../model/pthread-fiber-manager.cc:244
#3  0x00007ffff7aeb448 in ns3::TaskManager::SetFiberManagerType (this=0x6d9340, type=ns3::TaskManager::PTHREAD_FIBER_MANAGER) at ../model/task-manager.cc:509
#4  0x00007ffff7aed57c in ns3::Ptr<ns3::AttributeAccessor const> ns3::DoMakeAccessorHelperOne<ns3::EnumValue, ns3::TaskManager, ns3::TaskManager::FiberManagerType>(void (ns3::TaskManager::*)(ns3::TaskManager::FiberManagerType))::MemberMethod::DoSet(ns3::TaskManager*, ns3::EnumValue const*) const (this=0x69b0f0, object=0x6d9340, v=0x6d8c80)
    at /home/testbed/FNCS-install/include/ns3.26/ns3/attribute-accessor-helper.h:384
#5  0x00007ffff7aee029 in ns3::AccessorHelper<ns3::TaskManager, ns3::EnumValue>::Set (this=0x69b0f0, object=0x6d9340, val=...)
    at /home/testbed/FNCS-install/include/ns3.26/ns3/attribute-accessor-helper.h:188
#6  0x00007ffff517ca57 in ns3::ObjectBase::DoSet (this=this@entry=0x6d9340, accessor=..., checker=..., value=...) at ../src/core/model/object-base.cc:186
#7  0x00007ffff517dbfb in ns3::ObjectBase::ConstructSelf (this=this@entry=0x6d9340, attributes=...) at ../src/core/model/object-base.cc:165
#8  0x00007ffff5180320 in ns3::Object::Construct (this=this@entry=0x6d9340, attributes=...) at ../src/core/model/object.cc:145
#9  0x00007ffff51ccb61 in ns3::ObjectFactory::Create (this=0x7fffffffd680) at ../src/core/model/object-factory.cc:103
#10 0x00007ffff7b5f2ad in ns3::ObjectFactory::Create<ns3::TaskManager> (this=0x7fffffffd680) at /home/testbed/FNCS-install/include/ns3.26/ns3/object-factory.h:200
#11 0x00007ffff7b5dd3c in ns3::DceManagerHelper::Install (this=0x7fffffffd620, node=...) at ../helper/dce-manager-helper.cc:112
#12 0x00007ffff7b5dc86 in ns3::DceManagerHelper::Install (this=0x7fffffffd620, nodes=...) at ../helper/dce-manager-helper.cc:104
#13 0x0000000000411dac in main (argc=1, argv=0x7fffffffdb28) at ../myscripts/multispeak/model/RADICS_Exercise2_Utility1_AMI_1day.cc:227
